name: 'Tweet action'
description: 'Tweet in Twitter via GitHub Actions'
author: 'SnowCait'
inputs:
  status:
    required: true
    description: 'The text of the status update. URL encode as necessary. t.co link wrapping will affect character counts.'
  media_paths:
    description: |
      Upload media path(s).
      Size restrictions for uploading via API
        * Image 5MB
        * GIF 15MB
        * Video 15MB
outputs:
  response:
    description: 'Response JSON'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'edit'
  color: 'blue'
