name: 'Tweet action'
description: 'Tweet action'
author: 'SnowCait'
inputs:
  status:
    required: true
    description: 'The text of the status update. URL encode as necessary. t.co link wrapping will affect character counts.'
outputs:
  response:
    description: 'Response JSON'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'edit'
  color: 'blue'
