name: npm-check-updates

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/npm-check-updates.yml

jobs:
  update:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Versions
        run: |
          node --version
          npm --version
      - run: npm install -g npm-check-updates
      - run: ncu -u
      - run: npm install
      - run: npm audit fix
      - run: npm run build
      - run: npm run format
      - run: npm run lint
      - run: npm run package
      - run: npm test
        env:
          CONSUMER_API_KEY: ${{ secrets.CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
